name = "Angus Modpack"
author = "Ocawesome101"
version = "0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eea18e2368a8eb2ef766b731bf144d852f6a0ba2740ac2ecce361068209680d4"

[versions]
forge = "40.1.73"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1", "1.18.2"]
