name = "Angus Modpack"
author = "Ocawesome101"
version = "0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a160b35ce767ef9f4361fad4bf80aa431baf35ffa1c8c8a84d0a925d510481fa"

[versions]
forge = "40.1.73"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1", "1.18.2"]
